### PR TITLE
Update parser

### PR DESCRIPTION
**Pull request by larynjahor**
The BSU devs have decided to mess up the template so I had to shift some values.
The table now uses more grade ranges as it's also been changed by the devs.

### CODE REVIEW

**Comment by larynjahor** [comment]
We should also save the last parsing time stamp to check it before parsing so that we don't parse the site too many times.
But idk how often does the table update.

**Comment by al1enjesus** [comment]
> The BSU devs have decided to mess up the template so I had to shift some values.
> The table now uses more grade ranges as it's also been changed by the devs.

Yep, that's why I've decided to update it.

**Comment by al1enjesus** [comment]
> We should also save the last parsing time stamp to check it before parsing so that we don't parse the site too many times.
> But idk how often does the table update.

Last time I checked, approximately 30 min (28-32min), but not always.

**Comment by al1enjesus** [comment]
Updated parser, updated applicants life

**Review by al1enjesus — CHANGES_REQUESTED** [review]
Updated parser, updated applicants life.

**Review by al1enjesus — APPROVED** [review]
Updated parser, updated applicants life.

**Pull request merged**
